name: Sync Garmin Global to Garmin CN

on:
  workflow_dispatch:  # 手动触发[6,11](@ref)
  schedule:
    - cron: '0 */6 * * *'  # 每6小时UTC时间自动触发[6,11](@ref)

env:
  # 中国区账号凭证
  GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
  
  # 国际区账号凭证 
  GARMIN_GLOBAL_USERNAME: ${{ secrets.GARMIN_GLOBAL_USERNAME }}
  GARMIN_GLOBAL_PASSWORD: ${{ secrets.GARMIN_GLOBAL_PASSWORD }}
  
  # 全量迁移配置
  GARMIN_MIGRATE_NUM: "100"  # 单次最大迁移数量[11](@ref)
  GARMIN_MIGRATE_START: "0"    # 从第一条记录开始

  # 辅助配置
  BARK_KEY: ${{ secrets.BARK_KEY }}  # 通知密钥[6](@ref)
  TZ: Asia/Shanghai           # 时区设置[11](@ref)

jobs:
  full-sync:
    runs-on: ubuntu-latest
    name: Full Data Sync
    steps:
      # 代码检出
      - name: Checkout code
        uses: actions/checkout@v4  # 升级到Node20版本[1](@ref)
        with:
          persist-credentials: false

      # 环境配置
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'

      # 依赖安装
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 数据迁移
      - name: Run full sync
        run: yarn sync_global
        env:
          FORCE_MIGRATE: "true"  # 强制全量覆盖[11](@ref)
        timeout-minutes: 30      # 延长超时时间[6](@ref)

      # 结果提交
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Full sync completed"
          branch: main

      # 通知模块
      - name: Send notification
        if: always()
        uses: finab/action-bark@v2
        with:
          url: ${{ env.BARK_KEY }}
          title: "Sync Result"
          group: GarminSync
          body: "${{ job.status }} - Full sync completed at $(date)"
