name: Sync Garmin Global to Garmin CN

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨执行同步任务

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Sync Garmin Global to Garmin CN
        env:
          GARMIN_CN_USERNAME: ${{ secrets.GARMIN_CN_USERNAME }}
          GARMIN_CN_PASSWORD: ${{ secrets.GARMIN_CN_PASSWORD }}
          GARMIN_GLOBAL_USERNAME: ${{ secrets.GARMIN_GLOBAL_USERNAME }}
          GARMIN_GLOBAL_PASSWORD: ${{ secrets.GARMIN_GLOBAL_PASSWORD }}
          GARMIN_MIGRATE_NUM: ${{ secrets.GARMIN_MIGRATE_NUM }}
          GARMIN_MIGRATE_START: ${{ secrets.GARMIN_MIGRATE_START }}
        run: |
          # 在此处添加同步逻辑
          # 例如，使用curl命令调用佳明API来同步数据
          # 以下是一个示例，您需要根据实际API文档进行修改
          curl -X POST https://api.garmin.com/sync \
            -H "Content-Type: application/json" \
            -d "{ \"username\": \"$GARMIN_CN_USERNAME\", \"password\": \"$GARMIN_CN_PASSWORD\", \"global_username\": \"$GARMIN_GLOBAL_USERNAME\", \"global_password\": \"$GARMIN_GLOBAL_PASSWORD\", \"migrate_num\": \"$GARMIN_MIGRATE_NUM\", \"migrate_start\": \"$GARMIN_MIGRATE_START\" }"
